#!/usr/bin/env bash

# Determine the os.
os_name=$(uname)
case $os_name in
    "Darwin")
        node_name=$os_name
        ;;
    "Linux")
        node_name=$(uname --nodename) # Linux distro name
        ;;
esac

echo -e "The current operating system is $node_name\n"

# list of packages that I want to install. c_pkg as common packages, f_pkg
# for Fedora, and m_pkg for MacOs homebrew.
c_pkg=(
    bat
    cloc
    fastfetch
    fd
    fzf
    git
    lazygit
    starship
    ripgrep
    neovim
    zoxide
    tldr
    tmux
    stow
)
f_pkg=(
    # eza and nerd fonts need to use curl
    # also eza needs both bash completion and the man files
    # Not doing eza and font for now
    vim
    alacritty
    chromium-browser
)
m_pkg=(
    borders
    ghostty
    eza
    aerospace
    utm
    iian
#    localsend
    sketchybar
    font-hack-nerd-font
    font-sketchybar-app-font
    font-jetbrains-mono-nerd-font
)

# define the fedora install function
fedora_install(){
    sudo dnf copr enable atim/starship
    sudo dnf copr enable dejan/lazygit
    sudo dnf update
    max="${#c_pkg[@]}"
    for (( i=0; i<$max; i++)); do
        sudo dnf install "${c_pkg[i]}"
    done
    max1="${#f_pkg[@]}"
    for (( i=0; i<$max1; i++)); do
        sudo dnf install "${f_pkg[i]}"
    done
    sudo dnf clean all
}

# define the fedora install function
mac_install(){
    brew --version &>/dev/null || curl -fsSL https://raw.githubusercontent.com/Hombrew/install/HEAD/install.sh
    max="${#c_pkg[@]}"
    for (( i=0; i<$max; i++)); do
        brew install "${c_pkg[i]}"
    done
    max1="${#m_pkg[@]}"
    for (( i=0; i<$max; i++)); do
        brew install "${m_pkg[i]}"
    done
    brew update && brew upgrade && brew cleanup --prune=all
}

case $node_name in
    "fedora")
        fedora_install
        ;;
    "Darwin")
        mac_install
        ;;
esac
