#!/usr/bin/env bash

# Determine the os.
os_name=$(uname)
case $os_name in
    "Darwin")
        node_name=$os_name
        ;;
    "Linux")
        node_name=$(uname --nodename) # Linux distro name
        ;;
esac

echo -e "The current operating system is $node_name\n"

# list of packages that I want to install. c_pkg as common packages, f_pkg
# for Fedora, and m_pkg for MacOs homebrew.
c_pkg=(
    ghostty
    bat
    eza
    cloc
    fastfetch
    fd
    fzf
    git
    lazygit
    starship
    ripgrep
    vim
    # neovim
    zoxide
    tmux
    stow
    glow
    mpv
    yt-dlp
    yazi
)
f_pkg=(
    # eza and nerd fonts need to use curl
    # also eza needs both bash completion and the man files
    # Not doing eza and font for now
    alacritty
    chromium-browser
    tldr
    okular
    cmake
    @c-development
    # zathura
    # zathura-pdf-poppler
)
m_pkg=(
    pandoc
    borders
    aerospace
    neovim
    utm
    tlrc
    #    localsend
    sketchybar
    font-hack-nerd-font
    font-sketchybar-app-font
    font-jetbrains-mono-nerd-font
    # yazi dependencies
    ffmpeg-full
    sevenzip
    jq
    poppler
    resvg
    imagemagick-full
    font-symbols-only-nerd-font
)

# define the fedora install function
fedora_install() {
    sudo dnf copr enable -y scottames/ghostty
    sudo dnf copr enable -y atim/starship
    sudo dnf copr enable -y dejan/lazygit
    sudo dnf copr enable -y lihaohong/yazi
    sudo dnf upgrade -y
    max="${#c_pkg[@]}"
    for ((i = 0; i < $max; i++)); do
        sudo dnf install -y "${c_pkg[i]}"
    done
    max1="${#f_pkg[@]}"
    for ((i = 0; i < $max1; i++)); do
        sudo dnf install -y "${f_pkg[i]}"
    done
    sudo dnf clean all
}

# define the sddm login screen function
sddm_setup() {
    sudo cp ./3-ristretto.jpg /usr/share/backgrounds/
    str="[General]\nbackground=/usr/share/backgrounds/3-ristretto.jpg"
    sddm_theme_conf="/usr/share/sddm/themes/03-sway-fedora/theme.conf"
    [[ -e $sddm_theme_conf ]] || sudo touch $sddm_theme_conf
    echo -e $str | sudo tee $sddm_theme_conf &&
        echo "sddm theme changed successfully"
}

# define the fedora install function
mac_install() {
    brew --version &>/dev/null \
        || curl -fsSL \
        https://raw.githubusercontent.com/Hombrew/install/HEAD/install.sh
    max="${#c_pkg[@]}"
    for ((i = 0; i < $max; i++)); do
        brew install "${c_pkg[i]}"
    done
    max1="${#m_pkg[@]}"
    for ((i = 0; i < $max; i++)); do
        brew install "${m_pkg[i]}"
    done
    brew update && brew upgrade && brew cleanup --prune=all
}

case $node_name in
    "fedora")
        fedora_install
        stow --restow -t ~ fedora_home
        sddm_setup
        ;;
    "Darwin")
        mac_install
        stow --restow -t ~ mac_home
        ;;
esac
