#!/usr/bin/env bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
source "$PLUGIN_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

# sketchybar --bar position=top height=25 y_offset=5 blur_radius=30 color=0x40000000
appearance=(
	position=top
	height=25
	y_offset=5
	blur_radius=30
	color=$BAR
)
sketchybar --bar "${appearance[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
	padding_left=5
	padding_right=5
	icon.font="Hack Nerd Font:Bold:17.0"
	label.font="Hack Nerd Font:Bold:16.0"
	icon.color=$GREEN
	label.color=$BLACKGREEN
	background.color=$BACKGROUND
	background.corner_radius=5
	background.height=18
	icon.padding_left=4
	icon.padding_right=4
	label.padding_left=4
	label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add event aerospace_workspace_change
for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=0x44ffffff \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

app_icon=(
	front_app
	icon.color=$BLUE
	icon.font="sketchybar-app-font:Regular:16.0"
	label.color=$BLACKGREEN
	script="$PLUGIN_DIR/front_app.sh"
)
sketchybar --add item chevron left \
	--set chevron icon= label.drawing=off icon.color=$BLACK0 \
	--add item front_app left \
	--subscribe front_app front_app_switched
sketchybar --set "${app_icon[@]}"

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
	--set clock update_freq=10 icon=󰃰 script="$PLUGIN_DIR/clock.sh" \
	--add item volume right \
	--set volume script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change \
	--add item battery right \
	--set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
	--subscribe battery system_woke power_source_change

# Playaround a bit

brew_f=(
	brew_f
	width=0
	icon.drawing=off
	label.color=$BLACK
	label.font="Hack Nerd Font:Bold:8.0"
	label.y_offset=4
	update_freq=86400
	script="$PLUGIN_DIR/brew_f.sh"
)
brew_cask=(
	brew_cask
	width=75
	icon=""
	icon.color=$BLACK
	icon.align=left
	label.font="Hack Nerd Font:Bold:8.0"
	label.color=$BLACKGREEN
	label.align=center
	label.y_offset=-4
	update_freq=86400
	script="$PLUGIN_DIR/brew_cask.sh"
)

sketchybar -m --add item brew_f q \
	--set "${brew_f[@]}" \
	--add item brew_cask q \
	--set "${brew_cask[@]}"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
