[main]
# Environment & Shell
term=xterm-256color

# Font settings
font=JetBrainsMonoNL Nerd Font:size=13
font-bold=JetBrainsMonoNL Nerd Font:style=Bold:size=13
font-italic=JetBrainsMonoNL Nerd Font:style=Italic:size=13

# Window adjustments
pad=10x10

[cursor]
style=beam
blink=no
beam-thickness=2

[mouse]
hide-when-typing=yes

[colors-dark]
# Note: Foot hex values must omit the leading '#'
background=0a0c10
foreground=f0f3f6

# Cursor colors
cursor=39c5cf 71b7ff

## Normal colors
regular0=7a828e  # black
regular1=ff9492  # red
regular2=26cd4d  # green
regular3=f0b72f  # yellow
regular4=71b7ff  # blue
regular5=cb9eff  # magenta
regular6=39c5cf  # cyan
regular7=d9dee3  # white

## Bright colors
bright0=9ea7b3   # black
bright1=ffb1af   # red
bright2=4ae168   # green
bright3=f7c843   # yellow
bright4=91cbff   # blue
bright5=cb9eff   # magenta
bright6=39c5cf   # cyan
bright7=d9dee3   # white

[key-bindings]
# Triggers 'CreateNewWindow' equivalent
spawn-terminal=Control+Shift+n

[text-bindings]
# Format: <shortcut> = <escaped hex string to send>
