[env]
TERM = "xterm-256color"

[terminal]
shell = { program = "/opt/homebrew/bin/bash", args = ["--login", "-i"] }

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 14

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "6", mods = "Control", chars = "\u001e" },
]

# (Github Dark High Contrast) Colors for Alacritty
[colors]
  # Default colors
  primary = {
    background = '#0a0c10',
    foreground = '#f0f3f6'
}

  # Cursor colors
  #
  # These will only be used when the `custom_cursor_colors` field is set to `true`.
  cursor = {
    text = '#0a0c10',
    # cursor = '#f0f3f6'
    cursor = '#71b7ff'
  }

  # Normal colors
  normal = {
    black = '#7a828e',
    red = '#ff9492',
    green = '#26cd4d',
    yellow = '#f0b72f',
    blue = '#71b7ff',
    magenta = '#cb9eff',
    cyan = '#39c5cf',
    white = '#d9dee3'
  }

  # Bright colors
  bright= {
    black = '#9ea7b3',
    red = '#ffb1af',
    green = '#4ae168',
    yellow = '#f7c843',
    blue = '#91cbff',
    magenta = '#cb9eff',
    cyan = '#39c5cf',
    white = '#d9dee3'
  }
