set nocompatible
syntax on
filetype plugin indent on
set relativenumber
set number
set shiftwidth=4
set tabstop=4
set expandtab
set ruler
set hlsearch
set incsearch
set scrolloff=10
set sidescrolloff=25


"Customise status line:
set statusline=[%f]
set statusline+=%m
set statusline+=%r
set statusline+=%h
set statusline+=%=
set statusline+=FileType: 
set statusline+=%y
set statusline+=\ 
set statusline+=\--
set statusline+=%p%%
set statusline+=\--
set statusline+=\ 
set statusline+=row:
set statusline+=%l/%L
set statusline+=\ 
set statusline+=col:
set statusline+=%c
set laststatus=2


