[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[terminal]
shell = { program = "cmd.exe", args = [
    "/k",
    "\"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\Tools\\VsDevCmd.bat\"",
    "-startdir=none",
    "-arch=x64",
    "-host_arch=x64"
] }

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
decorations = "Full"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
size = 13

[cursor]
style = { shape = "Beam", blinking = "On" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "/", mods = "Control", chars = "\u001f" },
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "6", mods = "Control", chars = "\u001e" },
]

# (Github Dark High Contrast) Colors for Alacritty
[colors]
  # Default colors
  primary = {
    background = '#0a0c10',
    foreground = '#f0f3f6'
}

  # Cursor colors
  #
  # These will only be used when the `custom_cursor_colors` field is set to `true`.
  cursor = {
    text = '#0a0c10',
    cursor = '#71b7ff'
    # cursor = '#f0f3f6'
  }

  # Normal colors
  normal = {
    black = '#7a828e',
    red = '#ff9492',
    green = '#26cd4d',
    yellow = '#f0b72f',
    blue = '#71b7ff',
    magenta = '#cb9eff',
    cyan = '#39c5cf',
    white = '#d9dee3'
  }

  # Bright colors
  bright= {
    black = '#9ea7b3',
    red = '#ffb1af',
    green = '#4ae168',
    yellow = '#f7c843',
    blue = '#91cbff',
    magenta = '#cb9eff',
    cyan = '#39c5cf',
    white = '#d9dee3'
  }
