-- For compatible reasons, the icons and group is defined inside the
-- plugins/whichkey.lua
vim.g.mapleader = " "
vim.keymap.set("n", "<leader>e", "<Cmd>Oil<CR>", { desc = "Explorer" })
vim.keymap.set("n", "<leader>n", "<Cmd>tabnew<CR>", { desc = "New file" })
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Go to left window", remap = true })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Go to right window", remap = true })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Go to lower window", remap = true })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Go to upper window", remap = true })
vim.keymap.set("n", "<S-h>", "<Cmd>bp<CR>", { desc = "Previous buffer" })
vim.keymap.set("n", "<S-l>", "<Cmd>bn<CR>", { desc = "Next buffer" })
vim.keymap.set("n", "<leader>q", "<Cmd>copen<CR>", { desc = "Quickfix List" })
-- temp test
-- vim.keymap.set("n", "<leader>j", function()
--   require("config.c_template").c_template()
-- end, { desc = "temp test function" })

-- Comment above the line and below the line
vim.keymap.set("n", "gco", "o<Esc>Vcx<Esc><Cmd>normal gcc<CR>fxa<BS>", { desc = "Comment below" })
vim.keymap.set("n", "gcO", "O<Esc>Vcx<Esc><Cmd>normal gcc<CR>fxa<BS>", { desc = "Comment above" })

-- Markdown Related
vim.keymap.set("n", "<leader>mt", function()
  require("render-markdown").buf_toggle()
end, { desc = "Toggle buf md render", remap = false })
vim.keymap.set("n", "<leader>mT", function()
  require("render-markdown").toggle()
end, { desc = "Toggle markdown render", remap = false })
vim.keymap.set("n", "<leader>mr", function()
  require("render-markdown").preview()
end, { desc = "preview markdown", remap = false })

-- Restart session
vim.keymap.set("n", "<leader>r", function()
  vim.cmd("restart!")
end, { desc = "restart!" })

-- Terminal
vim.keymap.set("n", "<leader>t", function()
  vim.cmd("terminal")
end, { noremap = true, desc = "Terminal" })
vim.keymap.set("n", "<leader>T", function()
  vim.cmd("vsplit")
  vim.cmd("terminal")
  vim.cmd("wincmd L")
end, { noremap = true, desc = "Terminal vsplit L" })
-- Hoping between terminal buffer and normal buffers
vim.keymap.set("t", "<C-j>", "<C-\\><C-n><C-w>j")
vim.keymap.set("t", "<C-k>", "<C-\\><C-n><C-w>k")
vim.keymap.set("t", "<C-h>", "<C-\\><C-n><C-w>h")
vim.keymap.set("t", "<C-l>", "<C-\\><C-n><C-w>l")

--
-- buffers
vim.keymap.set("n", "<leader>bd", "<Cmd>bd<CR>", { desc = "Delete the current buffer" })
vim.keymap.set("n", "<leader>bb", "<Cmd>Pick buffers<CR>", { desc = "mini.pick buffers" })
vim.keymap.set("n", "<leader>bp", "<Cmd>bp<CR>", { desc = "Previous buffer" })
vim.keymap.set("n", "<leader>bn", "<Cmd>bn<CR>", { desc = "Next buffer" })

-- mini.diff
vim.keymap.set("n", "<leader>o", "<Cmd>lua MiniDiff.toggle_overlay()<CR>", { desc = "git diff overlay" })

-- mini.pick
vim.keymap.set("n", "<leader> ", "<Cmd>Pick files<CR>", { desc = "mini.pick files" })
vim.keymap.set("n", "<leader>G", "<Cmd>Pick grep<CR>", { desc = "mini.pick grep" })
vim.keymap.set("n", "<leader>/", "<Cmd>Pick grep_live<CR>", { desc = "mini.pick live_grep" })
vim.keymap.set("n", "<leader>ff", function()
  require("config.Fengtao").pick_dir_file()
end, { desc = "pick dirs and files" })
vim.keymap.set("n", "<leader>fg", "<Cmd>Pick grep<CR>", { desc = "pick grep" })
vim.keymap.set("n", "<leader>fb", "<Cmd>Pick buffers<CR>", { desc = "pick buffers" })
vim.keymap.set("n", "<leader>f/", "<Cmd>Pick grep_live<CR>", { desc = "pick live grep" })
vim.keymap.set("n", "<leader>fh", "<Cmd>Pick help<CR>", { desc = "grep help docs" })
vim.keymap.set("n", "<leader>fc", function()
  require("config.Fengtao").pick_config()
end, { desc = "pick config" })

-- Code related, mason and stuff
vim.keymap.set("n", "<leader>cm", "<Cmd>Mason<CR>", { desc = "Mason TUI" })
vim.keymap.set("n", "<leader>cc", "<Cmd>checkhealth vim.lsp<CR>", { desc = "check lsp info" })
vim.keymap.set("n", "<leader>cC", "<Cmd>checkhealth nvim-treesitter<CR>", { desc = "check nvim-treesitter parsers" })
vim.keymap.set("n", "<leader>ct", "<Cmd>Inspect<CR>", { desc = "treesitter Inspect" })
vim.keymap.set("n", "<leader>cT", "<Cmd>InspectTree<CR>", { desc = "treesitter InspectTree" })
vim.keymap.set("n", "<leader>cd", "<Cmd>lua vim.diagnostic.setqflist()<CR>", { desc = "Diagnostics list" })
vim.keymap.set("n", "<leader>cr", function()
  require("config.Fengtao").execute_file_with_args()
end, { desc = "run with arguments" })
vim.keymap.set("n", "<leader>ci", function()
  require("config.Fengtao").swap_indent_highlight()
end, { desc = "swap indentscope state" })
vim.keymap.set("n", "<leader>cx", function()
  require("config.Fengtao").execute_file_with_args(true)
end, { desc = "run with args in term" })
vim.keymap.set("n", "<leader>x", function()
  require("config.Fengtao").execute_file()
end, { desc = "Execute or Compile" })
vim.keymap.set("n", "gd", "<Cmd>lua vim.lsp.buf.definition()<CR>", { desc = "Definition goto" })
vim.keymap.set("n", "gD", "<Cmd>lua vim.lsp.buf.declaration()<CR>", { desc = "Declaration goto" })

-- vim.pack
vim.keymap.set("n", "<leader>pv", function()
  vim.pack.update(nil, { offline = true })
end, { desc = "pack list" })
vim.keymap.set("n", "<leader>pu", function()
  vim.pack.update(nil, { force = true })
end, { desc = "pack update all" })

-- nvim-dap
vim.keymap.set("n", "<leader>dc", function()
  require("dap").continue()
end, { desc = "Debug continue" })
vim.keymap.set("n", "<leader>dt", function()
  require("dap").terminate()
end, { desc = "Terminate session" })
vim.keymap.set("n", "<leader>db", function()
  require("dap").toggle_breakpoint()
end, { desc = "Toggle breakpoint" })
vim.keymap.set("n", "<leader>dB", function()
  require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "Breakpoint condition" })
vim.keymap.set("n", "<leader>dv", "<Cmd>DapViewToggle<CR>", { desc = "Toggle dap-view" })
vim.keymap.set("n", "<leader>dC", function()
  require("dap").run_to_cursor()
end, { desc = "Run to Cursor" })
vim.keymap.set("n", "<leader>dg", function()
  require("dap").goto_()
end, { desc = "Go to Line (No Execute)" })
vim.keymap.set("n", "<leader>di", function()
  require("dap").step_into()
end, { desc = "Step Into" })
vim.keymap.set("n", "<leader>dj", function()
  require("dap").down()
end, { desc = "Down" })
vim.keymap.set("n", "<leader>dk", function()
  require("dap").up()
end, { desc = "Up" })
vim.keymap.set("n", "<leader>dl", function()
  require("dap").run_last()
end, { desc = "Run Last" })
vim.keymap.set("n", "<leader>do", function()
  require("dap").step_out()
end, { desc = "Step Out" })
vim.keymap.set("n", "<leader>dO", function()
  require("dap").step_over()
end, { desc = "Step Over" })
vim.keymap.set("n", "<leader>dr", function()
  require("dap").restart()
end, { desc = "Restart debug" })
vim.keymap.set("n", "<leader>ds", function()
  require("dap").session()
end, { desc = "Session" })
