vim.pack.add({ "https://github.com/folke/which-key.nvim" })

local icons = require("mini.icons")
git_icons, _, _ = icons.get("filetype", "git")
conf_icons, _, _ = icons.get("filetype", "config")

opts = {
  preset = "helix",
  spec = {
    { "<leader> ", icon = { icon = "󰱽", hl = "MiniIconsAzure" } },
    { "<leader>e", icon = { icon = "󰙅", hl = "MiniIconsBlue" } },
    { "<leader>n", icon = { icon = "󰝒", hl = "MiniIconsGreen" } },
    { "gh", icon = { icon = git_icons, hl = "MiniIconsOrange" } },
    { "gH", icon = { icon = git_icons, hl = "MiniIconsOrange" } },
    { "<leader>f", group = "mini.pick", icon = { icon = "󰍉", hl = "MiniIconsCyan" } },
    { "<leader>fh", icon = { icon = "󰋖", hl = "MiniIconsRed" } },
    { "<leader>fg", icon = { icon = "󰮮", hl = "MiniIconsPurple" } },
    { "<leader>f/", icon = { icon = "󰍉", hl = "MiniIconsRed" } },
    { "<leader>ff", icon = { icon = "󰱽", hl = "MiniIconsAzure" } },
    { "<leader>fb", icon = { icon = "", hl = "MiniIconsAzure" } },
    { "<leader>fc", icon = { icon = conf_icons, hl = "MiniIconsBlue" } },
    { "<leader>G", icon = { icon = "󰍉", hl = "MiniIconsGreen" } },
    { "<leader>/", icon = { icon = "󰍉", hl = "MiniIconsRed" } },
    { "<leader>b", group = "buffers", icon = { icon = "", hl = "MiniIconsYellow" } },
    { "<leader>bb", icon = { icon = "", hl = "MiniIconsGreen" } },
    { "<leader>bd", icon = { icon = "", hl = "MiniIconsRed" } },
    { "<leader>bp", icon = { icon = "", hl = "MiniIconsAzure" } },
    { "<leader>bn", icon = { icon = "", hl = "MiniIconsOrange" } },
    { "<leader>q", icon = { icon = "", hl = "MiniIconsRed" } },
    { "<leader>m", group = "markdown", icon = { icon = "", hl = "MiniIconsBlue" } },
    { "<leader>mr", icon = { icon = "󰕮", hl = "MiniIconsGreen" } },
    { "<leader>mt", icon = { icon = "󰨚", hl = "MiniIconsOrange" } },
    { "<leader>mT", icon = { icon = "⏼", hl = "MiniIconsRed" } },
    -- NOTE1: harpoon not working with vim.pack.add() yet
    -- {"<leader>H", icon = { icon = "󰛢", hl = "MiniIconsPurple"}},
    -- {"<leader>h", icon = {icon = "󰀱", hl = "MiniIconsPurple"}},
    -- {"<leader>fH", icon = { icon = "󰛢", hl = "MiniIconsPurple"}},
    -- {"<leader>0", hidden = true},
    -- {"<leader>1", icon = { icon = "󱡀", hl = "MiniIconsPurple"}},
    -- {"<leader>2", icon = { icon = "󱡀", hl = "MiniIconsPurple"}},
    -- {"<leader>3", icon = { icon = "󱡀", hl = "MiniIconsPurple"}},
    -- {"<leader>4", icon = { icon = "󱡀", hl = "MiniIconsPurple"}},
    -- {"<leader>5", icon = { icon = "󱡀", hl = "MiniIconsPurple"}},
    -- {"<leader>6", icon = { icon = "󱡀", hl = "MiniIconsPurple"}},
    -- {"<leader>7", icon = { icon = "󱡀", hl = "MiniIconsPurple"}},
    -- {"<leader>8", icon = { icon = "󱡀", hl = "MiniIconsPurple"}},
    -- {"<leader>9", icon = { icon = "󱡀", hl = "MiniIconsPurple"}},
    { "gx", icon = { icon = "󱅷", hl = "MiniIconsBlue" } },
    { "<leader>r", icon = { icon = "󰜉", hl = "MiniIconsRed" } },
    { "<leader>c", group = "code", icon = { icon = "", hl = "MiniIconsGreen" } },
    { "<leader>cc", icon = { icon = "", hl = "MiniIconsOrange" } },
    { "<leader>cC", icon = { icon = "", hl = "MiniIconsGreen" } },
    { "<leader>cT", icon = { icon = "", hl = "MiniIconsGreen" } },
    { "<leader>ct", icon = { icon = "", hl = "MiniIconsGreen" } },
    { "<leader>cd", icon = { icon = "", hl = "MiniIconsPurple" } },
    { "<leader>cr", icon = { icon = "", hl = "MiniIconsAzure" } },
    { "<leader>p", group = "vim.pack", icon = { icon = "󰏓", hl = "MiniIconsBlue" } },
    { "<leader>pu", icon = { icon = "󰏔", hl = "MiniIconsBlue" } },
    { "<leader>d", group = "debug", icon = { icon = "", hl = "MiniIconsGreen" } },
    { "<leader>dc", icon = { icon = "", hl = "MiniIconsBlue" } },
    -- { "<leader>da", icon = { icon = "", hl = "MiniIconsOrange" } },
    { "<leader>dt", icon = { icon = "", hl = "MiniIconsRed" } },
    { "<leader>dr", icon = { icon = "󰜉", hl = "MiniIconsRed" } },
    { "<leader>di", icon = { icon = "", hl = "MiniIconsRed" } },
    { "<leader>do", icon = { icon = "", hl = "MiniIconsRed" } },
    { "<leader>dO", icon = { icon = "", hl = "MiniIconsRed" } },
    { "<leader>dB", icon = { icon = "󰮍", hl = "MiniIconsRed" } },
    { "<leader>dl", icon = { icon = "󰘁", hl = "MiniIconsRed" } },
    { "<leader>dt", icon = { icon = "", hl = "MiniIconsRed" } },
    { "<leader>dk", icon = { icon = "", hl = "MiniIconsRed" } },
    { "<leader>dj", icon = { icon = "", hl = "MiniIconsRed" } },
    { "<leader>dv", icon = { icon = "󱢈", hl = "MiniIconsRed" } },
    { "<leader>x", icon = { icon = "", hl = "MiniIconsAzure" } },
  },
}

local whichkey = require("which-key")
whichkey.setup(opts)
